project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!local/"
  pre-render:
    - quarto-scripts/papers.r
    - quarto-scripts/files.r
  post-render: 
    - quarto-scripts/reveal2pdf.r
    - quarto-scripts/pdfsubset.r
  resources:
    - papers/*.pdf
    - slides/files/*.pdf
    - slides/sharing

website:
  favicon: resources/hex.svg
  title: "ADCOM"
  navbar:
    #background: "#786fa6"
    search: true
    right:
      - icon: github
        href: https://github.com/stat-teaching/adcom
        aria-label: GitHub

author: 
  - name: "Filippo Gambarota PhD"
    email: filippo.gambarota@unipd.it
    twitter: fgambarota
    github: filippogambarota
    orcid: "0000-0002-6666-1747"

institute: "Università di Padova"

execute: 
  freeze: auto

format:
  html:
    theme:
      - pulse
      - brand
    css: styles.css
    toc: true
    anchor-sections: true

bibliography: "https://raw.githubusercontent.com/filippogambarota/bib-database/main/references.bib"
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl"
