{
  "hash": "061cb435b29a03e032c3be1f0366c81c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Modello di Regressione Lineare\npdf: \"[{{< fa file-pdf >}}](slides/07-modello-lineare.pdf)\"\npdf-pages: 36\n---\n\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n## Dataset\n\nLavoriamo sempre sul dataset @Di-Marco2020-wu:\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndat <- readxl::read_xlsx(\"dimarco2020.xlsx\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n  id age gender   education status residence period age_cat period_cat\n1  1  53   male high_school      2     south     31   51-60        >31\n2  2  60   male      degree      2     north     27   51-60      21-30\n3  3  40 female      degree      2     north     13   31-40      11-15\n4  4  57   male      degree      2     north     20   51-60      16-20\n5  5  60   male high_school      2     north     20   51-60      16-20\n6  6  46   male      degree      2     north     14   41-50      11-15\n  attachment needs bonds perc_collective_efficacy perc_self_efficacy family\n1       3.67  3.33  3.33                      3.2               3.11   3.75\n2       4.00  3.33  4.00                      4.2               3.95   5.00\n3       4.00  2.67  3.50                      3.8               3.58   4.25\n4       4.00  4.00  3.50                      3.6               3.74   4.25\n5       3.33  3.00  3.33                      3.4               3.53   4.00\n6       4.00  3.33  3.33                      4.2               3.63   5.00\n  friends organization burnout trauma satisfaction extrinsic intrinsic quest\n1    4.00         4.00     1.8   2.11          4.0      2.75      6.00  1.67\n2    4.25         3.25     1.4   0.60          3.5      4.75      6.50  1.00\n3    4.50         4.50     2.7   2.30          3.6      5.75      5.50  5.00\n4    4.50         4.50     1.9   1.80          3.0      4.50      7.00  2.75\n5    3.25         3.75     2.6   2.30          2.7      4.25      3.75  4.50\n6    5.00         4.75     2.1   1.30          2.6      4.75      7.00  1.25\n  desiderability\n1           3.86\n2           4.00\n3           4.00\n4           3.14\n5           3.86\n6           3.57\n\n```\n\n\n:::\n:::\n\n\n## Relazione lineare\n\nQuando abbiamo parlato di *correlazione*, abbiamo chiarito che due variabili sono correlate se la loro relazione è di tipo *lineare*. Lineare significa che la relazione può essere descritta da una retta. **Ma come disegniamo questa retta?**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-7-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Infinite rette\n\nIn uno spazio bidimensionale come questo grafico, possiamo disegnare infinite rette:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-8-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Come scegliere la retta migliore?\n\nIntuitivamente, l'idea è di prendere una retta che *approssima meglio* la relazione tra le due variabili. Prendiamo come metrica di bontà della retta la distanza dai punti:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-9-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Come scegliere la retta migliore?\n\nPer quantificare in un numero questa metrica, eleviamo al quadrato (togliamo il segno) e facciamo la somma. Calcoliamo quindi la devianza o Sum of Squares (SS):\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-10-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Come scegliere la retta migliore?\n\nQuesto valore di per se non ci dice molto ma riassume la somma delle distanze (al quadrato) dalla retta. Facciamolo per diverse rette.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-11-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Come scegliere la retta migliore?\n\nCome vediamo, diverse rette producono una diversa SS. Ovviamente, più piccola è la SS e più vicini sono i punti alla retta. Questo è il nostro criterio, dobbiamo trovare la retta che *minimizza* la distanza dei punti (al quadrato).\n\nQuesto metodo, dal punto di vista algoritmico, si chiama **metodo dei minimi quadrati** perchè appunto permette di trovare quella retta che minimizza la distanza dai punti (al quadrato).\n\n## Come disegnare una retta?\n\nPrima di tutto però è necessario capire come una retta viene definita. Abbiamo detto che per un piano bidimensionale passano infinite rette. Allora intanto ancoriamoci ad un punto:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-12-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Come disegnare una retta?\n\nOra immaginiamo che tutte le rette (ancora infinite) passino da quel punto. Di base ci serve solo definire l'inclinazione della retta.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-13-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Come disegnare una retta?\n\nQuindi abbiamo bisogno di soli 2 elementi per disegnare una retta. Un punto di *ancoraggio* e un valore che indichi la pendenza della retta. Questi due valori sono chiamati rispettivamente **intercetta** e **pendenza** o coefficiente angolare (*slope*).\n\nPiù formalmente, una retta è definita come:\n\n$$\ny_i = \\beta_0 + \\beta_1 x_i\n$$\n\nDove $\\beta_0$ è l'intercetta e $\\beta_1$ è la pendenza. Nella pratica è una funzione con due parametri che dato un input $x$ fornisce il valore di $y$. Il valore di $y$ dipenderà dai valori di $\\beta_0$ e $\\beta_1$.\n\n## Intercetta\n\nNella pratica, l'intercetta sposta verticalmente la retta. Qui la pendenza è la stessa ma sto spostando verticalmente tutta la retta.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-14-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Disegnare la retta, migliore\n\nQuindi come disegniamo la retta migliore? L'idea è quella di trovare un modo per *minimizzare* la distanza della retta dai punti. In questo modo siamo in grado di stimare i parametri $\\beta_0$ e $\\beta_1$. In particolare, $\\beta_1$:\n\n$$\n\\beta_1 = \\frac{\\sum^n_{i = 1} (x - \\bar{x})(y - \\bar{y})}{\\sum^n_{i = 1}{(x - \\bar{x})^2}}\n$$\n\nInvece $\\beta_0$:\n\n$$\n\\beta_0 = \\bar{y} - \\beta_1 \\bar{x}\n$$\n\n::: aside\nIl metodo dei minimi quadrati dimostra che questo modo di calcolare $\\beta_0$ e $\\beta_1$ è quello che minimizza le distanze (errori). La dimostrazione è fuori dallo scopo del corso.\n:::\n\n## Disegnare la retta, migliore\n\nProviamo a fare il calcolo, con le nostre due variabili:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- dat$burnout\ny <- dat$satisfaction\n\nb1 <- sum((x - mean(x)) * (y - mean(y))) / sum((x - mean(x))^2)\nb0 <- mean(y) - b1 * mean(x)\n\nb0\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.83504\n\n```\n\n\n:::\n\n```{.r .cell-code}\nb1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.5072002\n\n```\n\n\n:::\n:::\n\n\nAnche senza sapere bene come interpretarli, proviamo a disegnare la retta. Per disegnarla riprendiamo la formula generale della retta $y = \\beta_0 + \\beta_1 x$.\n\n## Disegnare la retta, migliore\n\nPer disegnarla prendiamo una serie di valori $x$ e su ogni $x$ applichiamo la formula. Usiamo direttamente i valori di `burnout` (salvati in `x`)\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(x)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.8 1.4 2.7 1.9 2.6 2.1\n\n```\n\n\n:::\n\n```{.r .cell-code}\nyn <- b0 + b1 * x\n\n# questi sono i valori per disegnare la retta\nhead(yn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.922080 4.124960 3.465599 3.871360 3.516319 3.769919\n\n```\n\n\n:::\n:::\n\n\n## Disegnare la retta, migliore\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(x, yn)\n```\n\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-17-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Cosa sono effettivamente $\\beta_0$ e $\\beta_1$?\n\nLi abbiamo calcolati e visualizzato la retta, ma cosa vogliono dire quei numeri?\n\n- $\\beta_0$ (intercetta) è il valore di $y$ (outcome) quando $x = 0$. E' il punto dove la retta interseca l'asse $y$\n- $\\beta_1$ (pendenza, slope) è l'incremento di $y$ per ogni incremento unitario di $x$\n\nMentre $\\beta_0$ è molto semplice, vediamo meglio $\\beta_1$. L'idea è questa, prendiamo un intervallo di valori sulla $x$, tramite la retta proiettiamo quell'intervallo sulla $y$. La proiezione su $y$ è il nostro $\\beta_1$.\n\n## Cosa sono effettivamente $\\beta_0$ e $\\beta_1$?\n\nPiù formalmente, prendiamo due punti $a$ e $b$ sulla retta $x$ e calcoliamo la differenza, chiamiamolo $\\Delta_x$. Poi proiettiamo questa differenza su $y$ e calcoliamo la differenza, chiamiamolo $\\Delta_y$. Il rapporto tra queste due differenze è $\\beta_1$:\n\n$$\n\\beta_1 = \\frac{y_a - y_b}{x_a - x_b} = \\frac{\\Delta_y}{\\Delta_x}\n$$\n\nQuindi, quando $x_a - x_b = 1$ allora:\n\n$$\n\\begin{aligned}\ny &= \\beta_0 + \\beta_1 x \\\\\ny^{\\star} &= \\beta_0 + \\beta_1 (x + 1) \\\\\ny^{\\star} &= \\beta_0 + \\beta_1x + \\beta_1 \\\\\ny^{\\star} &= y + \\beta_1\n\\end{aligned}\n$$\n\n## Cosa sono effettivamente $\\beta_0$ e $\\beta_1$?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-18-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Cosa sono effettivamente $\\beta_0$ e $\\beta_1$?\n\nQuindi in termini pratici:\n\n- $\\beta_0$ (intercetta) è la stima di `satisfaction` (*outcome*) quando il `burnout` (*predittore*) è zero.\n- $\\beta_1$ (slope) è l'incremento di `satisfaction` per un incremento unitario di `burnout`. Essendo che $\\beta_1$ è negativo, questo è un decremento.\n\nCi sono due punti importanti per l'interpretazione dei valore di $\\beta_0$ e $\\beta_1$:\n\n- `burnout` messo a zero potrebbe non essere sensato. Immaginate di avere l'età al posto di burnout. $\\beta_0$ sarebbe il valore di `satisfaction` quando l'età è zero.\n- L'incremento unitario di `burnout` deve essere sensato. Se siamo 1 punto in più nella scala di burnout è un valore sensato, allora $\\beta_1$ diventa direttamente intepretabile.\n\n## Cosa stiamo effettivamente facendo?\n\nA prescindere dall'aspetto geometrico, cosa significa tracciare una retta e quindi trovare (stimare) i parametri $\\beta_0$ e $\\beta_1$. Per farlo partiamo da un caso particolare ovvero una retta con $\\beta_1 = 0$.\n\nSe riprendiamo le formule:\n$$\n\\begin{aligned}\n\\beta_0 &= \\bar{y} - \\beta_1 \\bar{x} \\\\\n\\beta_0 &= \\bar{y}\n\\end{aligned}\n$$\n\nQuindi quando $\\beta_1 = 0$, $\\beta_0$ corrisponde alla media di $y$ (`satisfaction` nel nostro caso).\n\n## Cosa stiamo effettivamente facendo?\n\nQuesta retta sta ignorando `burnout` ($\\beta_1 = 0$). Possiamo calcolare la SS sommando i segmenti rossi (al quadrato). Chiamiamo questa SS, SSE (errore):\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-19-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Cosa stiamo effettivamente facendo?\n\nOra se invece che fissare $\\beta_1 = 0$, usiamo `burnout` e vediamo se la retta si sposta:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-20-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Cosa stiamo effettivamente facendo?\n\nIn pratica la distanza tra la retta e i punti è, in media, ridotta. Vediamo per un punto in particolare. Spostare la retta (dalla rossa alla blu) *spiega* una parte della distanza (varianza).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-21-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Cosa stiamo effettivamente facendo?\n\nQuindi se chiamiamo $SS_E$ la somma dei quadrati rimasta dopo aver spostato la retta possiamo chiamare $SS_T$ (totale, riga verde) quella prima di spostare la retta. Invece chiamiamo $SS_R$ (regressione) quella che abbiamo tolto (in gergo, *spiegato*, blu). Possiamo quindi scrivere che:\n\n$$\n\\textcolor{green}{SS_T} = \\textcolor{blue}{SS_R} + \\textcolor{red}{SS_E}\n$$\n\nQuindi i parametri $\\beta_0$ e $\\beta_1$ vengono stimati (tramite il metodo dei minimi quadrati) in modo da minimizzare $\\textcolor{red}{SS_E}$ (o anche per massimizzare $\\textcolor{blue}{SS_R}$).\n\n## $R^2$\n\nInoltre, se $\\textcolor{green}{SS_T}$ è il nostro totale, possiamo esprimere il quale percentuale $\\textcolor{blue}{SS_R}$ spiega. Chiamiamo $R^2$ questa percentuale. Formalmente:\n\n$$\nR^2 = 1 - \\frac{\\textcolor{red}{SS_E}}{\\textcolor{green}{SS_T}}\n$$\n\nChiaramente maggiore è la riduzione di $\\textcolor{red}{SS_E}$ (la retta si avvicina molto ai punti) maggiore è $R^2$.\n\n## Intuizione\n\nUn'altro modo di vedere la questione è, partendo dalla retta con $\\beta_1 = 0$ (quella orizzontale). Senza un predittore $x$ (`burnout`) la retta che minimizza $\\textcolor{red}{SS_E}$ è fondamentalmente la media.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-22-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Intuizione\n\nQuando inseriamo un predittore `burnout` stiamo implicitamente dicendo che la media di $y$ (`satisfaction`) si può spostare in funzione di `burnout`. Quindi la retta che minimizza è sempre la media ma spostata in funzione di `burnout`:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-23-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Più formalmente\n\nOra che abbiamo idea di cosa sta succedendo, defininiamo meglio l'equazione della retta tenendo conto anche dell'errore:\n\n$$\n\\textcolor{green}{y_i} = \\textcolor{blue}{\\beta_0 + \\beta_1 x_i} + \\textcolor{red}{\\epsilon_i}\n$$\n\nDove $y_i$ è il valore *osservato* (di `satisfaction`). La parte $\\textcolor{blue}{\\beta_0 + \\beta_1 x_i}$ viene anche chiamata componente sistematica perchè definisce semplicemente la retta una volta stimati $\\beta_0$ e $\\beta_1$, senza errore. Il valore osservato è quindi formato dalla parte sistematica e dall'errore.\n\n## Errori\n\nOra, mentre la parte sistematica $\\textcolor{blue}{\\beta_0 + \\beta_1 x_i}$ per definizione è senza errore è importante ora capire di più riguardo a $\\textcolor{red}{\\epsilon_i}$.\n\nAbbiamo definito nel modulo di inferenza, che quando stimiamo dei parametri c'è sempre una quota d'errore. Inoltre questo **errore**, idealmente, dovrebbe essere di tipo **casuale** e non sistematico.\n\nQuindi gli errori $\\textcolor{red}{\\epsilon_i}$, attorno alla retta (parte sistematica) dovrebbero distribuirsi in modo casuale. In termini pratici i punti dovrebbero essere certe volte maggiori, altre volte minori della retta. La media degli errori quindi dovrebbe essere zero.\n\n## Errori\n\nPiù formalmente possiamo dire che:\n\n- La media degli errori dovrebbe essere $\\mu_{\\epsilon} = 0$\n- La dispersione degli errori $\\sigma_{\\epsilon}$ (la varianza/deviazione standard) è per definizione diversa da zero (c'è sempre una quota d'errore) ma aumenta/diminuisce in base a quanto la retta è vicina ai punti.\n\nQuindi un buon modo di descrivere gli errori (idealmente) potrebbe essere quello di immaginare una distribuzione $\\epsilon \\sim \\mathcal{D}(\\mu = 0, \\sigma_{\\epsilon})$.\n\n## Errori\n\nUna buona distribuzione potrebbe essere proprio quella **Normale**. Infatti essendo simmetrica le deviazioni dalla media sono per definizione casuali. Deviazioni positive e negative sono bilanciate attorno al centro, ovvero la media.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-24-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Errori\n\nQuindi possiamo dire che costruiamo una retta che, tramite $\\beta_0$ e $\\beta_1$ minimizza le distanze dai punti. Le distanze *residue* sono distribuite in modo casuale come una distribuzione normale con $\\mu = 0$ e deviazione standard $\\sigma_{\\epsilon}$.\n\n$$\ny_i = \\beta_0 + \\beta_1 x_i + \\epsilon_i\n$$\n\n$$\n\\epsilon_i \\sim \\mathcal{N}(0, \\sigma_{\\epsilon_i})\n$$\n\nDefiniamo anche $\\hat{y}$ (ovvero $y$ stimato) come:\n\n$$\n\\hat{y_i} = \\beta_0 + \\beta_1 x_i\n$$\n\nOvvero il valore che la retta prevede per l'osservazione $i$.\n\n## Errori, graficamente\n\nStiamo assumendo che per ogni $\\hat{y_i}$, gli errori intorno siano distribuiti come una normale con $\\mu = 0$ e deviazione standard $\\sigma_{\\epsilon}$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-25-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Perche $\\mu = 0$?\n\nSe provate a sottrarre (*centrare*) da ogni dato osservato $y_i$ il dato previsto dalla retta $\\hat{y_i}$ otteniamo questo. La deviazione standard di $y - \\hat{y}$ è una stima di $\\sigma_{\\epsilon}$.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-26-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Riassumendo\n\nAbbiamo *scomposto* ogni dato osservato $y_i$ come:\n\n$$\n\\textcolor{green}{y_i} = \\textcolor{blue}{\\beta_0 + \\beta_1 x_i} + \\textcolor{red}{\\epsilon_i}\n$$\n\nSe definiamo $\\textcolor{blue}{\\hat{y}} = \\beta_0 + \\beta_1 x_i$ allora:\n\n$$\n\\textcolor{green}{y_i} = \\textcolor{blue}{\\hat{y_i}} + \\textcolor{red}{\\epsilon_i}\n$$\n\nInoltre, definiamo come **residui**:\n\n$$\n\\textcolor{red}{\\epsilon_i} = \\textcolor{green}{y_i} - \\textcolor{blue}{\\hat{y_i}}\n$$\n\nInfine, quando $\\beta_1 = 0$ abbiamo visto che:\n\n$$\n\\textcolor{green}{y_i} = \\textcolor{blue}{\\beta_0} + \\textcolor{red}{\\epsilon_i}  = \\textcolor{blue}{\\bar{y}} + \\textcolor{red}{\\epsilon_i}\n$$\n\n## Riassumendo\n\nInoltre abbiamo definito gli errori come casuali ($\\mu = 0$) e distribuiti normalmente con deviazione standard $\\sigma_{\\epsilon}$. Possiamo quindi definire queste quantità:\n\n$$\n\\begin{aligned}\n\\textcolor{green}{SS_{T}} &= \\textcolor{blue}{SS_{R}} + \\textcolor{red}{SS_{E}} \\\\\n\\textcolor{green}{SS_{T}} &= \\sum^{n}_{i = 1} (y_i - \\bar{y})^2 \\\\\n\\textcolor{blue}{SS_{R}} &= \\sum^{n}_{i = 1} (\\hat{y_i} - \\bar{y})^2 \\\\\n\\textcolor{red}{SS_{E}} &= \\sum^{n}_{i = 1} (y_i - \\hat{y})^2 \\\\\nR^2 &= 1 - \\frac{\\textcolor{red}{SS_{E}}}{\\textcolor{green}{SS_{T}}}\n\\end{aligned}\n$$\n\n## Riassumendo\n\nQuesto che abbiamo definito è un modello lineare. Ogni modello lineare ha una parte sistematica $\\beta_0 + \\beta_1 x$ e una parte casuale $\\epsilon$. I parametri da stimare in questo caso sono quindi $\\beta_0$, $\\beta_1$ e $\\sigma_{\\epsilon}$.\n\nQuindi, una relazione tra due variabili, si può approssimare con una retta della quale dobbiamo stimare i parametri. Inoltre, i punti possono essere più o meno dispersi attorno alla retta stimata determinando più o meno errore di stima.\n\n## Stesso $\\beta_1$, diversa $\\sigma_{\\epsilon}$\n\nVediamo dei casi dove la pendenza/slope della retta è la stessa ma la deviazione standard dei residui cambia. Dove è più forte la relazione secondo voi?\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-27-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Stesso $\\beta_1$, diversa $\\sigma_{\\epsilon}$\n\nE' chiaro che la forza della relazione, in termini di pendenza è la stessa ma è chiaramente più intensa la relazione nel primo grafico. Il problema è che la variazione di $y$ e $x$ cambia da un grafico all'altro. Forse possiamo *standardizzare* in qualche modo.\n\nPartiamo standardizzando (trasformare in punti $z$) $x$, `burnout` nel nostro caso. Ora cambiamo l'unità di misura che diventa una deviazione standard.\n\nQuindi $\\beta_1$ diventa l'incremento di `satisfaction` quando `burnout` cresce di una deviazione standard.\n\n## Stesso $\\beta_1$, diversa $\\sigma_{\\epsilon}$\n\nQuindi, all'aumentare di una deviazione standard di `burnout`, `satisfaction` diminuisce di 0.29.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-28-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Stesso $\\beta_1$, diversa $\\sigma_{\\epsilon}$\n\nVediamolo in pratica, vi ricordo la formula:\n\n$$\n\\beta_1 = \\frac{\\sum^n_{i = 1} (x - \\bar{x})(y - \\bar{y})}{\\sum^n_{i = 1}{(x - \\bar{x})^2}}\n$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# standardizzo il burnout e metto su x per comodità\nx <- (dat$burnout - mean(dat$burnout)) / sd(dat$burnout)\n\n# metto su y per comodità\ny <- dat$satisfaction\n\nsum((x - mean(x)) * (y - mean(y))) / \n  sum((x - mean(x))^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.2945735\n\n```\n\n\n:::\n:::\n\n\n## Stesso $\\beta_1$, diversa $\\sigma_{\\epsilon}$\n\nOra proviamo a *standardizzare* anche `satisfaction`. $\\beta_1$ ci dirà di quante deviazioni standard aumenta `satisfaction` all'aumentare di una deviazione standard di `burnout`.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-30-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Stesso $\\beta_1$, diversa $\\sigma_{\\epsilon}$\n\nVediamolo in R:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# standardizzo il burnout e metto su x per comodità\nx <- (dat$burnout - mean(dat$burnout)) / sd(dat$burnout)\n\n# metto su y per comodità\ny <- (dat$satisfaction - mean(dat$satisfaction)) / sd(dat$satisfaction)\n\nsum((x - mean(x)) * (y - mean(y))) / \n  sum((x - mean(x))^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.5549457\n\n```\n\n\n:::\n:::\n\n\nCalcoliamo anche la correlazione:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncor(x, y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.5549457\n\n```\n\n\n:::\n:::\n\n\n## Stesso $\\beta_1$, diversa $\\sigma_{\\epsilon}$\n\nCome vedete, standardizzando le variabili $\\beta_1$ equivale alla correlazione. Esiste infatti una relazione diretta:\n\n$$\n\\beta_1 = r_{xy} \\frac{\\sigma_y}{\\sigma_x}\n$$\n\nTrovare la miglior retta che minimizza la SS equivale a calcolare il coefficiente di correlazione.\n\nChiaramente nei tre grafici con $\\sigma_{\\epsilon}$ diversa essendo fissa la parte sistematica $\\beta_0 + \\beta_1 x$ allora la varianza di $y$ è maggiore. Se $\\sigma_y$ aumenta per mantenere lo stesso rapporto (abbiamo fissato $\\beta_1$) necessariamente $r_{xy}$ deve scendere. Per questo se calcoliamo la correlazione, questa diminuisce (a parità di $\\beta_1$) all'aumentare della dispersione attorno alla retta ($\\sigma_{\\epsilon}$).\n\n\n## Riassumendo\n\n- Il metodo dei minimi quadrati ci permette di disegnare, stimando $\\beta_0$ e $\\beta_1$ la miglior retta\n- I coefficienti sono rispettivamente la media di $y$ quando $x = 0$ e l'incremento di $y$ per incremento unitario di $x$\n- Una volta definita la retta, abbiamo una componente sistematica $\\beta_0 + \\beta_1x$ e una componente d'errore (casuale) $\\epsilon$\n- Minore è la distanza dei punti dalla retta, minore è la $SS_E$ e quindi maggiore è $R^2$\n- La dispersione dei punti attorno alla retta stimata viene catturata dal parametro $\\sigma_{\\epsilon}$\n\n## Modello statistico\n\nQuello che abbiamo costruito passo per passo è un **modello di regressione lineare**. Ma cosa si intende per modello statistico?\n\nUn modello statistico è un **modello matematico che descrive, in modo semplificato, la relazione tra variabili**. Quello che viene definito processo generativo dei dati (data-generating process).\n\nOgni modello statistico ha una parte **sistematica** e una parte d'**errore (casuale)**. L'obiettivo è quindi, tramite un campione, **stimare** la componente sistematica.\n\nOgni modello statistico, per definizione, fa delle **assunzioni**. Queste assunzioni sono necessarie per trarre conclusioni appropriate. Il modello statistico quindi non scopre la realtà ma cerca di capire se i dati (e di conseguenza la popolazione) possono essere approssimati tramite le assunzioni/vincoli del modello stesso.\n\n## Modello statistico\n\nIn generale, possiamo descrivere un modello statistico come:\n\n$$\ny = f(\\mathbf{X}) + \\epsilon\n$$\n\nDove $y$ è la variabile *outcome*, $\\mathbf{X}$ sono i predittori (grassetto per indicare uno o più predittori, $x_1$, $x_2$, etc.) $\\epsilon$ è l'errore e $f(\\cdot)$ è la parte sistematica del modello.\n\nNel nostro caso $\\epsilon \\sim \\mathcal{N}(0, \\sigma_{\\epsilon})$ e $f() = \\beta_0 + \\beta_1 x$ è uno dei modelli possibili e queste sono *assunzioni*. Assumendo che la relazione sia lineare e che gli errori siano distribuiti normalmente, $f() = \\beta_0 + \\beta_1 x$ descrive i dati.\n\n## Esempio\n\nImmaginiamo di avere dei dati di questo tipo. E' chiaro che la relazione non è *lineare*. Se stimiamo la nostra retta qui otteniamo questo:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-33-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Esempio\n\nProviamo a rappresentare graficamente $\\epsilon$ (i residui) vs i valori stimati dal modello (retta blu del grafico precedente).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-34-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Esempio\n\nE' chiaro che pur avendo stimato la retta che minimizza la $SS_E$ questa non sia una buona approssimazione dei dati. Ci serve un modello più complesso:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-35-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Esempio\n\nQuesti sono i residui in questo caso. La retta non era una buona approssimazione.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-36-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Esempio\n\nQuesti due modelli differiscono per $f()$. Uno è più semplice (la retta) ma evidenti problematiche. L'altro è più complesso ($\\beta_2$ e $\\beta_3$) da stimare ma approssima meglio.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-37-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Messaggio finale\n\n> All models are wrong, but some are useful. </br> -- *George Box*\n\nQuindi, i modelli statistici sono semplificazioni matematiche della realtà tramite assunzioni e vincoli.\n\nIl modello lineare ad esempio, assume che una retta sia una buona approssimazione della realtà. Modelli più complessi possono approssimare meglio ma richiedono anche più parametri.\n\nI parametri vengono *stimati* (con errore) e la qualità della stima è funzione della variabilità del fenomeno e del numero di osservazioni.\n\nModelli complessi richiedono maggior numero di informazione (soggetti) per essere stimati in modo affidabile.\n\n# Modello lineare\n\n## Modello lineare\n\nOra ci focalizziamo sul modello lineare con la consapevolezza che $f()$ possa essere molte cose. Formalmente:\n\n$$\n\\mathbf{y}_{n\\times1} = \\mathbf{X}_{n \\times p}\\boldsymbol{\\beta}_{p \\times 1} + \\boldsymbol{\\epsilon}_{n \\times 1}\n$$\n\nIl grassetto (o matrix formulation) è un modo compatto per scrivere anche modelli lunghi. Infatti possiamo avere:\n\n$$\ny_i = \\beta_0 + \\beta_1 x_{1_i} + \\beta_2 x_{2_i} + \\epsilon_i\n$$\n\n## Modello lineare semplice\n\nQuello che abbiamo usato fino ad ora $\\beta_0 + \\beta_1 x$ è definito **modello lineare semplice** perchè abbiamo un solo predittore $x$. Ovviamente i modelli possono avere anche molti predittori, in quel caso si chiamano **modelli lineari multipli**.\n\n## Terminologia\n\nDefiniamo della terminologia utile:\n\n- con **valori osservati** $y_i$ intendiamo la combinazione di componente sistematica $\\mathbf{X}\\boldsymbol{\\beta}$ ed errore $\\epsilon$.\n- con **valori predetti** $\\mu_i$ intendiamo la sola componente sistematica $\\mathbf{X}\\boldsymbol{\\beta}$ (senza errore). Sono i valori esattamente sulla retta.\n- con **residui** intendiamo la componente di errore $\\epsilon_i$ ovvero la differenza $y_i - \\mu_i$\n\n## Predittore categoriale\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nProviamo ad inserire un predittore categoriale a due livelli `sex`. L'outcome è l'`altezza` (per vedere una chiara differenza)^[Stiamo usando in nostri dati del questionario]:\n\n\n::: {.cell layout-align=\"center\" output-location='slide'}\n\n```{.r .cell-code}\nboxplot(altezza ~ sex, data = adcom)\n```\n\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-39-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Predittore categoriale\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-40-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Predittore categoriale\n\nProviamo a farlo direttamente in R:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfit <- lm(altezza ~ sex, data = adcom)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = altezza ~ sex, data = adcom)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.3517  -4.3517  -0.8077   5.6483  13.6483 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 164.3517     0.3540  464.33   <2e-16 ***\nsexMaschile  12.4559     0.9768   12.75   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.565 on 394 degrees of freedom\nMultiple R-squared:  0.2922,\tAdjusted R-squared:  0.2904 \nF-statistic: 162.6 on 1 and 394 DF,  p-value: < 2.2e-16\n\n```\n\n\n:::\n:::\n\n\n## Predittore categoriale\n\nPer capire quello che sta succedendo prima dobbiamo capire cosa succede a `sex` quando entra in un modello lineare.\n\nL'idea è che nonostante la variabili categoriali siano non numeriche (superficialmente) possiamo rappresentare la stessa informazione usando $k - 1$ (dove $k$ è il numero di modalità) variabili numeriche.\n\nIn questo caso, `sex` ha due livelli quindi $k = 2$ e ci servono $k - 1 = 1$ variabili numeriche. Di base si usano quelle che si chiamano **dummy-variables** ovvero variabili con valore 0 o 1.\n\n## Dummy variables\n\nLa funzione `lm` crea automaticamente queste variabili quando inseriamo dei predittori categoriali. Per vedere quello che succede possiamo usare la funzione `model.matrix()`:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmodel.matrix(~ sex, data = adcom)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    (Intercept) sexMaschile\n1             1           0\n2             1           0\n3             1           0\n4             1           0\n5             1           0\n6             1           0\n7             1           0\n8             1           0\n9             1           0\n10            1           0\n11            1           1\n12            1           0\n13            1           0\n14            1           0\n15            1           1\n16            1           0\n17            1           0\n18            1           1\n19            1           0\n20            1           0\n21            1           0\n22            1           0\n23            1           1\n24            1           0\n25            1           0\n26            1           0\n27            1           0\n28            1           0\n29            1           0\n30            1           0\n31            1           0\n32            1           0\n33            1           0\n34            1           0\n35            1           0\n36            1           1\n37            1           0\n38            1           0\n39            1           0\n40            1           0\n41            1           0\n42            1           0\n43            1           0\n44            1           0\n45            1           0\n46            1           1\n47            1           0\n48            1           0\n49            1           0\n50            1           0\n51            1           0\n52            1           0\n53            1           1\n54            1           0\n55            1           0\n56            1           0\n57            1           0\n58            1           0\n59            1           0\n60            1           1\n61            1           0\n62            1           0\n63            1           0\n64            1           0\n65            1           0\n66            1           0\n67            1           1\n68            1           0\n69            1           0\n70            1           0\n71            1           0\n72            1           0\n73            1           0\n74            1           0\n75            1           0\n76            1           0\n77            1           0\n78            1           0\n79            1           0\n80            1           0\n81            1           0\n82            1           0\n83            1           0\n84            1           0\n85            1           0\n86            1           0\n87            1           0\n88            1           0\n89            1           1\n90            1           0\n91            1           0\n92            1           0\n93            1           0\n94            1           0\n95            1           1\n96            1           0\n97            1           0\n98            1           0\n99            1           0\n100           1           0\n101           1           0\n102           1           0\n103           1           1\n104           1           0\n105           1           0\n106           1           0\n107           1           0\n108           1           0\n109           1           1\n110           1           0\n111           1           0\n112           1           1\n113           1           1\n114           1           0\n115           1           0\n116           1           0\n117           1           1\n118           1           0\n119           1           1\n120           1           0\n121           1           0\n122           1           0\n123           1           0\n124           1           0\n125           1           1\n126           1           0\n127           1           0\n128           1           0\n129           1           0\n130           1           0\n131           1           0\n132           1           1\n133           1           0\n134           1           0\n135           1           0\n136           1           0\n137           1           0\n138           1           0\n139           1           0\n140           1           0\n141           1           0\n142           1           0\n143           1           1\n144           1           0\n145           1           0\n146           1           0\n147           1           0\n148           1           0\n149           1           0\n150           1           0\n151           1           0\n152           1           0\n153           1           0\n154           1           0\n155           1           0\n156           1           0\n157           1           0\n158           1           0\n159           1           0\n160           1           0\n161           1           0\n162           1           0\n163           1           0\n164           1           0\n165           1           0\n166           1           0\n167           1           0\n168           1           0\n169           1           0\n170           1           0\n171           1           0\n172           1           0\n173           1           0\n174           1           0\n175           1           0\n176           1           0\n177           1           0\n178           1           0\n179           1           0\n180           1           1\n181           1           0\n182           1           1\n183           1           0\n184           1           0\n185           1           0\n186           1           0\n187           1           0\n188           1           1\n189           1           0\n190           1           0\n191           1           0\n192           1           0\n193           1           0\n194           1           0\n195           1           0\n196           1           0\n197           1           0\n198           1           0\n199           1           0\n200           1           1\n201           1           0\n202           1           0\n203           1           1\n204           1           0\n205           1           0\n206           1           0\n207           1           0\n208           1           0\n209           1           0\n210           1           0\n211           1           0\n212           1           0\n213           1           0\n214           1           0\n215           1           0\n216           1           0\n217           1           0\n218           1           0\n219           1           0\n220           1           0\n221           1           0\n222           1           0\n223           1           0\n224           1           0\n225           1           0\n226           1           0\n227           1           0\n228           1           0\n229           1           0\n230           1           0\n231           1           0\n232           1           0\n233           1           0\n234           1           0\n235           1           0\n236           1           0\n237           1           0\n238           1           0\n239           1           0\n240           1           1\n241           1           1\n242           1           0\n243           1           0\n244           1           0\n245           1           0\n246           1           0\n247           1           0\n248           1           0\n249           1           0\n250           1           0\n251           1           0\n252           1           0\n253           1           0\n254           1           1\n255           1           0\n256           1           1\n257           1           0\n258           1           0\n259           1           0\n260           1           0\n261           1           0\n262           1           0\n263           1           0\n264           1           0\n265           1           0\n266           1           0\n267           1           0\n268           1           1\n269           1           0\n270           1           0\n271           1           1\n272           1           0\n273           1           0\n274           1           0\n275           1           0\n276           1           0\n277           1           0\n278           1           0\n279           1           0\n280           1           0\n281           1           0\n282           1           0\n283           1           1\n284           1           0\n285           1           0\n286           1           1\n287           1           0\n288           1           0\n289           1           0\n290           1           0\n291           1           0\n292           1           0\n293           1           0\n294           1           0\n295           1           0\n296           1           0\n297           1           0\n298           1           0\n299           1           0\n300           1           0\n301           1           0\n302           1           1\n303           1           0\n304           1           0\n305           1           1\n306           1           0\n307           1           0\n308           1           0\n309           1           0\n310           1           1\n311           1           0\n312           1           0\n313           1           0\n314           1           0\n315           1           1\n316           1           0\n317           1           0\n318           1           1\n319           1           0\n320           1           0\n321           1           0\n322           1           0\n323           1           0\n324           1           0\n325           1           0\n326           1           1\n327           1           0\n328           1           0\n329           1           0\n330           1           0\n331           1           1\n332           1           0\n333           1           1\n334           1           0\n335           1           1\n336           1           0\n337           1           1\n338           1           0\n339           1           0\n340           1           0\n341           1           0\n342           1           0\n343           1           1\n344           1           0\n345           1           1\n346           1           0\n347           1           0\n348           1           1\n349           1           0\n350           1           0\n351           1           0\n352           1           0\n353           1           0\n354           1           0\n355           1           0\n356           1           0\n357           1           0\n358           1           0\n359           1           1\n360           1           0\n361           1           0\n362           1           0\n363           1           0\n364           1           0\n365           1           0\n366           1           0\n367           1           0\n368           1           0\n369           1           0\n370           1           0\n371           1           0\n372           1           1\n373           1           0\n374           1           0\n375           1           0\n376           1           0\n377           1           1\n378           1           0\n379           1           0\n380           1           0\n381           1           0\n382           1           0\n383           1           0\n384           1           0\n385           1           1\n386           1           0\n387           1           0\n388           1           0\n389           1           0\n390           1           0\n391           1           0\n392           1           1\n393           1           0\n394           1           0\n395           1           0\n396           1           1\nattr(,\"assign\")\n[1] 0 1\nattr(,\"contrasts\")\nattr(,\"contrasts\")$sex\n[1] \"contr.treatment\"\n\n```\n\n\n:::\n:::\n\n\n## Dummy variables\n\nPossiamo lasciare stare l'intercetta per il momento, la colonna `sexMaschile` è la versione *dummy* della variabile categoriale `sex`. Possiamo anche crearla manualmente:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nhead(adcom$sex, 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"Femminile\" \"Femminile\" \"Femminile\" \"Femminile\" \"Femminile\" \"Femminile\"\n [7] \"Femminile\" \"Femminile\" \"Femminile\" \"Femminile\" \"Maschile\"  \"Femminile\"\n[13] \"Femminile\" \"Femminile\" \"Maschile\" \n\n```\n\n\n:::\n\n```{.r .cell-code}\nadcom$sex_dummy <- ifelse(adcom$sex == \"Maschile\", 1, 0) # o l'inverso\nhead(adcom$sex_dummy, 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1\n\n```\n\n\n:::\n:::\n\n\nNon è necessario farlo manualmente, ma è importante capire cosa fa il software. A prescindere da R, tendenzialmente tutti i software lavorano così.\n\n## Dummy variables\n\nQuindi quando inseriamo una variabile categoriale con $k$ livelli, vengono create $k - 1$ variabili *dummy*. Sono variabili numeriche a tutti gli effetti, quindi i coefficienti si intepretano come tali. Riprendiamo (concetriamoci sui parametri):\n\n\n::: {.cell layout-align=\"center\" lines='^Coefficients|^Signif'}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 164.3517     0.3540  464.33   <2e-16 ***\nsexMaschile  12.4559     0.9768   12.75   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Dummy variables\n\n- `(Intercept)` è il valore di $y$ (`altezza`) quando $x = 0$ (`sex`). `sex` = 0 per la variabile *dummy* è il sesso femminile. Quindi è l'altezza media delle femmine.\n- `sexMaschile` ($\\beta_1$) è l'incremento di `altezza` per incremento unitario in `sex`.\n\nEssendo che sono variabili dummy, dire *aumento unitario* equivale a dire mi sposto da una categoria all'altra. Quindi $\\beta_1$ è la **differenza di altezza tra maschi e femmine**.\n\n## T-test {.smaller}\n\nIn altri termini, abbiamo fatto sostanzialmente un t-test. Infatti possiamo confrontare i risultati. Notate i valori della statistica $t$ e $p$ value:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nt.test(altezza ~ sex, var.equal = TRUE, data = adcom)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  altezza by sex\nt = -12.752, df = 394, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group Femminile and group Maschile is not equal to 0\n95 percent confidence interval:\n -14.37629 -10.53561\nsample estimates:\nmean in group Femminile  mean in group Maschile \n               164.3517                176.8077 \n\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\" lines='^Coefficients|^Signif'}\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 164.3517     0.3540  464.33   <2e-16 ***\nsexMaschile  12.4559     0.9768   12.75   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n## Scriviamo l'equazione\n\nCon i modelli lineari, scrivere l'equazione (componente sistematica) è molto importante e fa capire molte cose.\n\n$$\n\\hat{\\mbox{altezza}} = \\beta_0 + \\beta_1 \\mbox{sex} \\quad \\mbox{sex} = \\{0, 1\\}\n$$\n$$\n\\begin{aligned}\n\\hat{\\mbox{altezza}} &= \\beta_0 + \\beta_1 \\times 1 \\quad \\mbox{sex} = 1 \\\\\n\\hat{\\mbox{altezza}} &= \\beta_0 + \\beta_1 \\times 0 \\quad \\mbox{sex} = 0 \\\\\n                     &= \\beta_0\n\\end{aligned}\n$$\n\n## Graficamente\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](07-modello-lineare_files/figure-revealjs/unnamed-chunk-47-1.svg){fig-align='center'}\n:::\n:::\n\n\n## Inferenza\n\nDa dove vengono quelle statistiche test $t$ e p value? Vengono calcolati esattamente come già sappiamo. Dobbiamo definire $H_0$ e $H_1$ anche nel caso di modelli di regressione lineare dove:\n\n$$\nH_0: \\beta_j = 0\n$$\n\n$$\nH_1: \\beta_j \\neq 0\n$$\n\nDove $\\beta_j$ è uno dei possibili coefficienti di regressione che siamo interessati a valutare. Ovviamente possiamo anche fare dei test monodirezionali.\n\n## Inferenza\n\nOgni coefficiente di regressione ha la sua stima campionaria $\\hat \\beta_j$ e quindi ha anche il suo errore standard $\\text{SE}_{\\hat \\beta_j}$ che indica quanto è precisa la stima del coefficiente di regressione. Quindi possiamo definire una statistica test standardizzata come:\n\n$$\nt = \\frac{\\hat \\beta_j}{\\text{SE}_{\\beta_j}}\n$$\n\nQuesta statistica test sotto $H_0$ si distribuisce come una $t$ di Student con $\\nu = n - p$ gradi di libertà dove $p$ è il numero totale di coefficienti stimati dal modello. Nel caso dell'altezza, $p = 2$ ($\\beta_0$ e $\\beta_1$) quindi $\\nu = n - p = 396 - 2 = 394$.\n\n## $R^2$ aggiustato\n\nNella tabella di regressione vedete anche il valore di $R^2$ aggiustato.\n\n$$\nR^2_{\\text{adj}} = 1 - \\frac{(1 - R^2)(n - 1)}{n - p}\n$$\n\nDove $n$ è la numerosità campionaria e $p$ il numero di coefficienti stimati. Sostanzialmente questa formula riduce il valore di $R^2$ in funzione del numero dei parametri stimati. A parità di $R^2$ (non aggiustato), quello aggiustato sarà minore se sono serviti più parametri per arrivare alla stessa varianza spiegata.\n\n## Assunzioni\n\nIl modello lineare funziona correttamente nel momento in cui alcune assunzioni sono rispettate:\n\n- **Linearità.** Si assume che la relazione tra $x$ e $y$ sia lineare, sia nella regressione semplice sia in quella multipla.\n- **Indipendenza.** I residui devono essere indipendenti tra loro. In sostanza, non devono esserci strutture sistematiche o fattori non misurati che li rendano dipendenti.\n- **Normalità.** Si assume che i residui siano distribuiti normalmente. Non è necessario che $x$ e $y$ siano normali, purché lo siano i residui.\n- **Omoscedasticità.** La varianza dei residui deve essere costante. In pratica, la dispersione dei residui deve rimanere simile per tutti i valori predetti $\\mu$ e, idealmente, per tutti i valori dei predittori $x$.\n\n## Linearità\n\nQuesta assunzione riguarda la **componente sistematica** del modello. In regressione lineare, “lineare” significa **lineare nei parametri**.\n\nAd esempio, questi sono modelli lineari:\n\n$$\ny = \\beta_0 + \\beta_1 x\n$$\n$$\ny = \\beta_0 + \\beta_1 x + \\beta_2 x^2\n$$\n\nè un modello lineare. Pur non rappresentando una retta, resta lineare perché i coefficienti $\\beta_0$, $\\beta_1$ e $\\beta_2$ compaiono linearmente.\n\n$$\ny = \\beta_0 + x^{\\beta_1}\n$$\n\nnon è un modello lineare, perché il parametro $\\beta_1$ compare come esponente e quindi non entra in forma lineare.\n\n## Indipendenza\n\nQuesta assunzione è *by-design* nel senso che dipende dal tipo di dato. In termini pratici significa che le righe del nostro dataset devono essere indipendenti. Indipendenza in questo caso significa, sostanzialmente, che ogni riga appartiene ad un soggetto diverso. Ad esempio:\n\n- 100 soggetti dove misuro $p$ variabili (questionari, socio-anagrafiche, etc.) -> dataset con righe indipendenti\n- 100 soggetti misurati prima/dopo un trattamento. Il valore pre e post sono correlati (dipendenti) perchè sono appartenenti allo stesso soggetto\n\nIn questo secondo caso è necessario usare dei modelli che tengano conto della dipendenza, come quelli multilivello. In tutti gli altri casi, il modello lineare che stiamo usando è adeguato.\n\n## Normalità dei residui\n\nLa normalità dei residui, come dice il nome significa che i residui (e non la variabile dipendente) devono essere distribuiti normalmente. In linea teorica, i residui devono avere media $\\mu = 0$ e $\\sigma = \\sigma_{\\epsilon}$ (quella stimata dal modello). Nella pratica devono avere una forma normale e non contenere pattern e/o deviazioni dalla media $\\mu = 0$.\n\nQuesta assunzione si vede principalmente a livello grafico e guardando statistiche descrittive dei residui. Alcuni propongono di usare dei test per valutare la normalità (tipo Shapiro-Wilk). Tuttavia il metodo migliore è quello grafico.\n\n## Omoscedasticità dei residui\n\nOltre alla normalità, il modello lineare richiede che la varianza dei residui $\\sigma_{\\epsilon}$ sia costante per ogni valore di $x$. In termini pratici, la dispersione attorno alla retta di regressione stimata deve essere costante.\n\nOvviamente questo è legato al fatto che stimando un solo parametro di varianza dei residui, questo per essere informativo non deve variare in funzione di $x$, altrimenti $\\sigma_{\\epsilon}$ diventa meno informativo.\n\nAnche questo criterio è facilmente verificabile a livello grafico e quindi consiglio di evitare i test statistici per questo tipo di cose.\n\n## Bibliografia",
    "supporting": [
      "07-modello-lineare_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}